### ISSUE TITLE
When instantiatas, current state is not loaded. 

### ISSUE THREAD

**Issue by casamia918** [fullcube/loopback-component-fsm#15]
Thank you for writing this mixin. While using, I found a problem. I'm using LB version 3. 

Problem is, the StateMachine does not load current state. When I print StateMachine's 'current' local variable after I load my model instance(of course by find method), it always undefined. Needless to say, the error message is "Invalid event in the current state". My model's stateProperty name is 'state'.

I temporarily detour this problem by passing "allowForce" option when call the event method. But it's annoying and defenitely looks like unintended behvior. Can you fix this?

**Comment by giano** [comment]
Same here.
